go.property("speed", 150)

function init(self)
	sound.play("#fundo", {gain = 0.9})
	self.input = {
		left = false,
		right = false,
		front = false,
		back = false
	}

	self.vel = vmath.vector3(0, 0, 0)

	msg.post(".", "acquire_input_focus")

	self.missoes = {
		{ texto = "Collect the 3 items", concluida = false, pontos = 200 },
		{ texto = " ", concluida = false, pontos = 100 }
	}
	self.pontos = 0
	self.documentos_coletados = 0
	self.total_documentos = 3

	msg.post ("main:/Interface#Interace", "atualizar_pontos", { valor = self.pontos })
	msg.post ("main:/Interface#Interace", "atualizar_missoes", { lista = self.missoes })
end

function update(self, dt)
	local dir = vmath.vector3()

	if self.input.left then dir.x = dir.x - 1 
	end
		
	if self.input.right then dir.x = dir.x + 1 
	end
	if self.input.front then dir.y = dir.y + 1 
	end
	if self.input.back then dir.y = dir.y - 1 
	end

	if dir.x ~= 0 or dir.y ~=0 then
		dir = vmath.normalize(dir)
		go.set_position(go.get_position() + dir * self.speed * dt)
	end

	-- Cria vetor de movimento total
	local movimento = vmath.vector3(dir.x * self.speed * dt, dir.y * self.speed * dt, 0)

	-- Move o objeto
	go.set_position(go.get_position() + movimento)

end


function on_input(self, action_id, action)
	if action_id == hash("left") then
		if action.pressed then
			self.input.left = true
			sound.play("#steps")
		elseif action.released then
			self.input.left = false
			sound.stop("#steps")
		end
	end
	if action_id == hash("right") then
		if action.pressed then
			self.input.right = true
			sound.play("#steps")
		elseif action.released then
			self.input.right = false
			sound.stop("#steps")
		end
	end
	if action_id == hash("front") then
		if action.pressed then
			self.input.front = true
			sound.play("#steps")
		elseif action.released then
			self.input.front = false
			sound.stop("#steps")
		end
	end
	if action_id == hash("back") then
		if action.pressed then
			self.input.back = true
			sound.play("#steps")
		elseif action.released then
			self.input.back = false
			sound.stop("#steps")
		end
	end
end

function concluir_missao(self, indice)
	print(self.missoes[indice].concluida)
	if not self.missoes[indice].concluida then
		self.missoes[indice].concluida = true
		self.pontos = self.pontos + self.missoes[indice].pontos
		msg.post("main:/Interface#Interace", "atualizar_pontos", { valor = self.pontos })
		msg.post("main:/Interface#Interace", "atualizar_missoes", { lista = self.missoes })
	end
	print(self.missoes[indice].concluida)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.normal.y > 0.1 then 
			self.input.back = false 
		end
		if message.normal.y < 0.1 then 
			self.input.front = false 
		end
		if message.normal.x > 0.1 then 
			self.input.left = false
		end
		if message.normal.x < 0.1 then 
			self.input.right = false
		end

		local pos = go.get_position()
		go.set_position(vmath.vector3(pos.x, pos.y, 0))
	end

	if message_id == hash("trigger_response") and message.enter then
		if message.other_group == hash("documento") then
			sound.play("#collect", {gain = 1.5})
			go.delete(message.other_id)
			self.documentos_coletados = self.documentos_coletados + 1
			if self.documentos_coletados >= self.total_documentos then
				concluir_missao(self, 1)
			end
		end

		if message.other_group == hash("Exit") then
			if self.missoes[1].concluida then
				concluir_missao(self, 2)
			end
		end

		if message.other_group == hash("Enemy") then
			print("Jogador detectado!")
			msg.post("main:/Interface", "flash_alerta")
			sound.play("#fx", {gain = 1.5})
		end
	end
end
	